# Generated by Django 6.0.4 on 2026-04-10 16:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("CLASSICAL", "Classical"),
                            ("COMEDY", "Comedy"),
                            ("COUNTRY", "Country"),
                            ("EASY_LISTENING", "Easy Listening"),
                            ("ELECTRONIC", "Electronic"),
                            ("FOLK", "Folk"),
                            ("HIP_HOP", "Hip-Hop"),
                            ("JAZZ", "Jazz"),
                            ("LATIN", "Latin"),
                            ("POP", "Pop"),
                            ("RNB_SOUL", "R&B and Soul"),
                            ("ROCK", "Rock"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("CALM", "Calm"),
                            ("ENERGETIC", "Energetic"),
                            ("HAPPY", "Happy"),
                            ("ROMANTIC", "Romantic"),
                            ("SAD", "Sad"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("BIRTHDAY", "Birthday"),
                            ("FESTIVE", "Festive"),
                            ("PARTY", "Party"),
                            ("RELAX", "Relax"),
                            ("WEDDING", "Wedding"),
                            ("WORKOUT", "Workout"),
                        ],
                        max_length=50,
                    ),
                ),
                ("audio_file", models.URLField(max_length=2048)),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[("PRIVATE", "Private"), ("PUBLIC", "Public")],
                        default="PRIVATE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("CLASSICAL", "Classical"),
                            ("COMEDY", "Comedy"),
                            ("COUNTRY", "Country"),
                            ("EASY_LISTENING", "Easy Listening"),
                            ("ELECTRONIC", "Electronic"),
                            ("FOLK", "Folk"),
                            ("HIP_HOP", "Hip-Hop"),
                            ("JAZZ", "Jazz"),
                            ("LATIN", "Latin"),
                            ("POP", "Pop"),
                            ("RNB_SOUL", "R&B and Soul"),
                            ("ROCK", "Rock"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("CALM", "Calm"),
                            ("ENERGETIC", "Energetic"),
                            ("HAPPY", "Happy"),
                            ("ROMANTIC", "Romantic"),
                            ("SAD", "Sad"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("BIRTHDAY", "Birthday"),
                            ("FESTIVE", "Festive"),
                            ("PARTY", "Party"),
                            ("RELAX", "Relax"),
                            ("WEDDING", "Wedding"),
                            ("WORKOUT", "Workout"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("PROCESSING", "Processing"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "song",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_request",
                        to="api.song",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
