# Generated by Django 6.0.4 on 2026-04-12 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_generationrequest_external_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="cover_color",
            field=models.CharField(
                blank=True,
                default="",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="cover_color must be a valid hex color like #A1B2C3",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="song_covers/"),
        ),
    ]
