# Generated by Django 6.0.4 on 2026-04-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_song_cover_color_song_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationrequest",
            name="generator_strategy",
            field=models.CharField(
                choices=[("mock", "Mock"), ("suno", "Suno")],
                default="suno",
                max_length=20,
            ),
        ),
    ]
